# Generated by Django 5.2.4 on 2025-09-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecard_02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='actual_weight',
            field=models.FloatField(default=0.0, help_text='Actual weight after allowance'),
        ),
        migrations.AddField(
            model_name='horse',
            name='apprentice_allowance',
            field=models.FloatField(default=0.0, help_text='Apprentice allowance'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Declared weight'),
        ),
    ]
