# Generated by Django 5.2.4 on 2025-09-19 13:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField()),
                ('race_no', models.IntegerField()),
                ('race_time', models.TimeField(default=datetime.time(0, 0))),
                ('race_field', models.CharField(max_length=100)),
                ('race_name', models.CharField(max_length=255)),
                ('race_distance', models.CharField(default='Unknown', max_length=50)),
                ('race_class', models.CharField(blank=True, max_length=100, null=True)),
                ('race_merit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('race_date', 'race_no', 'race_field')},
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_no', models.IntegerField(default=0)),
                ('horse_name', models.CharField(max_length=100)),
                ('blinkers', models.BooleanField(default=False)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('horse_merit', models.IntegerField(blank=True, null=True)),
                ('odds', models.CharField(blank=True, max_length=20, null=True)),
                ('race_class', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer', models.CharField(blank=True, max_length=100, null=True)),
                ('jockey', models.CharField(blank=True, max_length=100, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecard.race')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('class_score', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('jt_score', models.FloatField(blank=True, null=True)),
                ('jt_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('jockey', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer', models.CharField(blank=True, max_length=100, null=True)),
                ('class_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecard.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecard.race')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('position', models.CharField(max_length=10)),
                ('margin', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=20)),
                ('race_class', models.CharField(blank=True, max_length=100, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecard.horse')),
            ],
        ),
        migrations.CreateModel(
            name='HorseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.FloatField()),
                ('merit_score', models.FloatField()),
                ('form_score', models.FloatField()),
                ('class_score', models.FloatField()),
                ('distance_score', models.FloatField()),
                ('consistency_score', models.FloatField()),
                ('speed_rating', models.FloatField(blank=True, null=True)),
                ('stamina_index', models.FloatField(blank=True, null=True)),
                ('track_affinity', models.FloatField(blank=True, null=True)),
                ('jockey_score', models.FloatField(blank=True, null=True)),
                ('trainer_score', models.FloatField(blank=True, null=True)),
                ('days_since_last_run', models.IntegerField(blank=True, null=True)),
                ('recovery_score', models.FloatField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecard.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecard.race')),
            ],
            options={
                'unique_together': {('horse', 'race')},
            },
        ),
    ]
